spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/post-service
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
